USE [POTATO]
GO
BEGIN TRANSACTION
CREATE PARTITION FUNCTION [test1](datetime2(7)) AS RANGE LEFT FOR VALUES (N'2023-03-08T18:53:20')


CREATE PARTITION SCHEME [test1_schema] AS PARTITION [test1] TO ([PRIMARY], [PRIMARY])






ALTER TABLE [dbo].[T_Log] DROP CONSTRAINT [PK__T_Log__4A953BE508C461EA] WITH ( ONLINE = OFF )


SET ANSI_PADDING ON

ALTER TABLE [dbo].[T_Log] ADD PRIMARY KEY CLUSTERED 
(
	[Date_Time] ASC,
	[Employer] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [test1_schema]([Date_Time])








COMMIT TRANSACTION


